#!/usr/bin/env bash
# menu.sh — command line argument parsing, help output, and settings persistence.
# Sourced by build.sh before any build logic runs.
# Do NOT run this script directly.

# Guard against being sourced more than once
[[ -n "${MENU_SH_LOADED:-}" ]] && return
MENU_SH_LOADED=1

# Path to the user's saved feature selections.
# Gitignored — created on first successful configuration.
SETTINGS_FILE="$SCRIPT_DIR/build.cfg"

# Feature flags — defaults to off until explicitly enabled.
# These are set by parse_args() or load_settings() before the build runs.
FEATURE_SUBTITLES="n"
FEATURE_NVIDIA_FILTERS="n"
FEATURE_NON_FREE="n"
DRY_RUN="n"

# show_help()
# Prints usage information and exits.
show_help() {
  cat <<EOF
Usage: ./build.sh [options]

Options:
  -h, --help              Show this help message and exit
  -i, --interactive       Launch the interactive feature selection menu
      --subtitles         Enable text subtitle rendering (SRT, ASS/SSA)
                          Includes: freetype, fontconfig, harfbuzz, libass
      --nvidia-filters    Enable NVIDIA GPU-accelerated filters
                          Adds NPP headers for GPU-side pixel format conversion,
                          required for full GPU subtitle compositing pipeline
      --non-free          Enable proprietary codecs (fdk-aac, decklink)
                          Note: resulting binary cannot be redistributed
      --dry-run           Show what would be built without running anything
                          Can be combined with any feature flags

Feature sets:
  Base (always included)
    Core ffmpeg with H.264/H.265 encoding, NVIDIA NVENC/NVDEC hardware
    acceleration, image-based subtitle support (PGS, VOBSUB), and audio
    codec support including AAC, MP3, AC3, EAC3, DTS, TrueHD, FLAC, and PCM.

  Text subtitle rendering  (--subtitles)
    Adds burn-in support for text-based subtitles (SRT, ASS/SSA).
    Includes freetype, fontconfig, and libass.

  NVIDIA GPU filters  (--nvidia-filters)
    Adds NPP headers enabling GPU-side pixel format conversion, required
    to keep subtitle compositing fully on the GPU pipeline without
    dropping to CPU.

  Non-free  (--non-free)
    Adds proprietary codecs such as fdk-aac and decklink support.
    Resulting binary cannot be redistributed.

Examples:
  ./build.sh --subtitles
  ./build.sh --subtitles --nvidia-filters
  ./build.sh --subtitles --dry-run
  ./build.sh -i

On first run, no settings file exists. Pass options explicitly or use -i
to configure interactively. Selections are saved to build.cfg for
subsequent runs.
EOF
  exit 0
}

# save_settings()
# Writes current feature flag state to build.cfg.
save_settings() {
  cat > "$SETTINGS_FILE" <<EOF
# ffmpeg-windows-build-helpers feature selections
# Generated by build.sh — edit manually or re-run with -i to change.
FEATURE_SUBTITLES="${FEATURE_SUBTITLES}"
FEATURE_NVIDIA_FILTERS="${FEATURE_NVIDIA_FILTERS}"
FEATURE_NON_FREE="${FEATURE_NON_FREE}"
EOF
}

# load_settings()
# Reads feature flag state from build.cfg if it exists.
load_settings() {
  if [[ -f "$SETTINGS_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$SETTINGS_FILE"
  fi
}

# print_settings()
# Prints the current feature selections in a readable format.
print_settings() {
  echo "  Feature selections:"
  echo "    Base (always included)"
  [[ "$FEATURE_SUBTITLES"      == "y" ]] && echo "    Text subtitle rendering" || echo "    Text subtitle rendering  (off)"
  [[ "$FEATURE_NVIDIA_FILTERS" == "y" ]] && echo "    NVIDIA GPU filters"       || echo "    NVIDIA GPU filters        (off)"
  [[ "$FEATURE_NON_FREE"       == "y" ]] && echo "    Non-free codecs"          || echo "    Non-free codecs           (off)"
}

# show_dry_run()
# Prints what would be built without running anything.
show_dry_run() {
  echo ""
  echo "========================================"
  echo "  Dry run — nothing will be built"
  echo "========================================"
  echo ""
  print_settings
  echo ""
  echo "  Libraries that would be built:"
  echo ""
  echo "    ffmpeg"
  echo "        zlib              - lossless data compression"
  echo "        bzip2             - block-sorting file compression"
  echo "        nv-codec-headers  - NVIDIA NVENC/NVDEC/CUDA API headers"
  echo "        x264              - H.264/AVC encoder"
  echo "        x265              - H.265/HEVC encoder"
  if [[ "$FEATURE_SUBTITLES" == "y" ]]; then
    echo ""
    echo "        libass            - ASS/SSA and SRT subtitle rendering"
    echo "            libiconv          - character set conversion"
    echo "            libpng            - PNG image support"
    echo "            freetype          - font rendering engine"
    echo "                libpng        - -> already built for libass"
    echo "            harfbuzz          - text shaping engine"
    echo "            fribidi           - Unicode bidirectional algorithm (RTL text support)"
    echo "            fontconfig        - font discovery and matching"
    echo "                liblzma       - LZMA/XZ compression"
    echo "                libxml2       - XML parser"
  fi
  echo ""
  echo "  ffmpeg configure flags that would be used:"
  echo "    --disable-autodetect"
  echo "    --enable-gpl --enable-version3"
  echo "    --enable-libx264 --enable-libx265"
  echo "    --enable-nvenc --enable-nvdec --enable-cuda"
  echo "    --enable-cuvid --enable-cuda-llvm --enable-ffnvcodec"
  if [[ "$FEATURE_SUBTITLES" == "y" ]]; then
    echo "    --enable-libass --enable-fontconfig"
  fi
  if [[ "$FEATURE_NON_FREE" == "y" ]]; then
    echo "    --enable-nonfree --enable-libfdk-aac"
  fi
  echo ""
}

# parse_args()
# Processes command line arguments passed to build.sh.
# Sets feature flags and handles -h / -i.
# Usage: parse_args "$@"
parse_args() {
  local interactive="n"
  local explicit="n"   # tracks whether any feature flag was passed explicitly

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help)
        show_help
        ;;
      -i|--interactive)
        interactive="y"
        shift
        ;;
      --subtitles)
        FEATURE_SUBTITLES="y"
        explicit="y"
        shift
        ;;
      --nvidia-filters)
        FEATURE_NVIDIA_FILTERS="y"
        explicit="y"
        shift
        ;;
      --non-free)
        FEATURE_NON_FREE="y"
        explicit="y"
        shift
        ;;
      --dry-run)
        DRY_RUN="y"
        shift
        ;;
      *)
        echo "Error: unknown option '$1'"
        echo "Run ./build.sh --help for usage."
        exit 1
        ;;
    esac
  done

  # If -i was passed, launch whiptail menu (placeholder until menu.sh step 2)
  if [[ "$interactive" == "y" ]]; then
    echo "Interactive mode not yet implemented. Use --help to see available options."
    exit 0
  fi

  # No settings file and no explicit flags — print help and exit
  if [[ ! -f "$SETTINGS_FILE" ]] && [[ "$explicit" == "n" ]]; then
    echo "No configuration found. Please specify features or use -i for interactive setup."
    echo ""
    show_help
  fi

  # If explicit flags were passed, save them and proceed without prompting
  if [[ "$explicit" == "y" ]]; then
    save_settings
  else
    # No explicit flags — load from saved settings and confirm
    load_settings
    echo ""
    print_settings
    echo ""
    read -r -p "  Run with these settings? [Y/n/c(hange)]: " confirm
    case "${confirm,,}" in
      ""|y)
        # proceed
        ;;
      n)
        echo "Aborted."
        exit 0
        ;;
      c)
        echo "Interactive mode not yet implemented. Edit build.cfg directly or pass flags on the command line."
        exit 0
        ;;
      *)
        echo "Invalid selection. Aborted."
        exit 0
        ;;
    esac
    echo ""
  fi

  # Dry run — show what would happen and exit
  if [[ "$DRY_RUN" == "y" ]]; then
    show_dry_run
    exit 0
  fi
}
